<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginiaBotControlRequestTable extends Doctrine_Table
{
  public function getOrCreate($ip, sfGuardUser $user = null)
  {
    $botControl = Doctrine::getTable('iaBotControlRequest')->findOneByIp($ip);
    if (false == $botControl)
    {
      $botControl = new iaBotControlRequest();
      $botControl->setIp($ip);
      $botControl->setUser($user);
      $botControl->resetCredits();
      $botControl->save();
    }
    return $botControl;
  }
}