<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginiaBotControlRequest extends BaseiaBotControlRequest
{
  public function resetCredits()
  {
    $this->setCredits(intval(sfConfig::get('app_ia_bot_control_max_requests')));
    $this->save();
  }

  public function removeCredit()
  {
    $this->setCredits($this->getCredits() - 1);
  }
}